spring.application.name=demo
### Custom Properties for Mock API ###
mock.mock-api.base-url=http://localhost:8080/mock
mock.api.base-url=http://localhost:8080/api
mock.recording-enabled=true
mock.ldap=dummy_user
server.port=8082